version: '3'

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgresuno
      - POSTGRES_PASSWORD=postgresuno
    volumes:
      - ./postgres:/var/lib/postgresql/data
